# Generated by Django 6.0.1 on 2026-03-28 05:11

from django.db import migrations


def convert_roles_forward(apps, schema_editor):
    """Convert numeric role_num to string keys."""
    RoleLookup = apps.get_model('courses', 'RoleLookup')
    User = apps.get_model('courses', 'User')
    
    # Create mapping from old numeric role_num to new string role_num
    role_mapping = {
        '1': ('INST', 'INSTRUCTOR'),
        '2': ('STUD', 'STUDENT'),
        '3': ('ADMIN', 'ADMINISTRATOR'),
    }
    
    # Store old role IDs to new role IDs mapping
    id_mapping = {}
    
    # Create new RoleLookup entries with string keys
    for old_num, (new_num, role_name) in role_mapping.items():
        # Check if old numeric role exists
        old_role = RoleLookup.objects.filter(role_num=old_num).first()
        if old_role:
            id_mapping[old_role.id] = new_num
            # Create new role if it doesn't exist
            new_role, _ = RoleLookup.objects.get_or_create(
                role_num=new_num,
                defaults={'role_name': role_name}
            )
            
            # Update all users pointing to old role to new role
            User.objects.filter(role_id=old_role.id).update(role=new_role)
    
    # Delete old numeric roles
    RoleLookup.objects.filter(role_num__in=['1', '2', '3']).delete()


def convert_roles_backward(apps, schema_editor):
    """Revert to numeric role_num if needed."""
    RoleLookup = apps.get_model('courses', 'RoleLookup')
    User = apps.get_model('courses', 'User')
    
    # Revert mapping
    role_mapping = {
        'INST': ('1', 'INSTRUCTOR'),
        'STUD': ('2', 'STUDENT'),
        'ADMIN': ('3', 'ADMINISTRATOR'),
    }
    
    for new_num, (old_num, role_name) in role_mapping.items():
        # Get new string role
        new_role = RoleLookup.objects.filter(role_num=new_num).first()
        if new_role:
            # Create old numeric role if it doesn't exist
            old_role, _ = RoleLookup.objects.get_or_create(
                role_num=old_num,
                defaults={'role_name': role_name}
            )
            
            # Update all users pointing to new role to old role
            User.objects.filter(role=new_role).update(role=old_role)
    
    # Delete new string roles
    RoleLookup.objects.filter(role_num__in=['INST', 'STUD', 'ADMIN']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rolelookup_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(convert_roles_forward, convert_roles_backward)
    ]
