# Generated by Django 6.0.1 on 2026-03-28 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_convert_roles_to_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolelookup',
            options={'ordering': ['role_num']},
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
