# Generated by Django 6.0.3 on 2026-03-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_rolelookup_options_course_enrolled_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolled_students',
        ),
    ]
